web:
  build: .
  ports:
    - "1080:80"
    - "10443:443"
  volumes:
    - ../flyer:/var/www/flyer
  links:
    - mysqldb:mysqldb
mysqldb:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root